[package]
name = "deelevate"
version = "0.1.0"
authors = ["Wez Furlong"]
edition = "2018"
description = "Drop privileges on Windows"
license = "MIT"
documentation = "https://docs.rs/deelevate"
readme = "README.md"
keywords = ["UAC", "elevate", "privileges"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
winapi = { version = "0.3", features = [
  "errhandlingapi",
  "handleapi",
  "processthreadsapi",
  "securitybaseapi",
  "winerror",
  "winuser",
]}
