name: Continuous

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: "windows-2022"
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release --verbose
      - uses: actions/upload-artifact@v3
        with:
          name: omsi-elevate
          path: target/release/omsi-elevate.exe
  upload:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: omsi-elevate
      - uses: meeDamian/github-release@2.0
        with:
          tag: "Continuous"
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "omsi-elevate.exe"
          allow_override: true
