name: Continuous

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: "vs2017-win2016"
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - name: "Build Release"
      shell: bash
      run: |
        mkdir DeElevate
        mv target/release/eledo.exe target/release/eledo-pty-bridge.exe target/release/normdo.exe DeElevate/
        cp README.md LICENSE.md DeElevate
        7z a -tzip DeElevate.zip DeElevate
    - name: "Upload to Continuous Release"
      uses: wez/upload-release-assets@releases/v1
      with:
         files: "DeElevate.zip"
         release-tag: "Continuous"
         repo-token: "${{ secrets.GITHUB_TOKEN }}"

