name: Continuous

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: "windows-2022"
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - name: "Upload to Continuous Release"
      uses: AButler/upload-release-assets@v2.0
      with:
         files: "target/release/omsi-elevate.exe"
         release-tag: "Continuous"
         repo-token: "${{ secrets.GITHUB_TOKEN }}"
