name: Continuous

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: "windows-2022"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release --verbose
      - name: Upload plugin to release
        uses: wez/upload-release-assets@v2.0
        with:
          files: 'target/release/omsi-elevate.exe'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: "Continuous"
